module.exports = {
  port: 3001,
  espPath: '/esp',
  get authPassword() { return process.env.WEB_PASSWORD || ''; },

  devices: [
    {
      id: 'fan',
      name: 'Fan',
      actions: [
        { id: 'on', name: 'On', code: 0x1FE807F, protocol: 'NEC' },
        { id: 'off', name: 'Off', code: 0x1FEA05F, protocol: 'NEC' },
        { id: 'rotate', name: 'Rotate', code: 0x1FE40BF, protocol: 'NEC' },
      ],
    },
    {
      id: 'ac',
      name: 'Air Conditioner',
      type: 'ac',
      actions: [
        { id: 'set_state', name: 'Set State' },
      ],
    },
    {
      id: 'tv_samsung',
      name: 'TV (Samsung)',
      actions: [
        { id: 'power', name: 'Power', code: 0xE0E040BF, protocol: 'NEC' },
        { id: 'source', name: 'Source', code: 0xE0E0807F, protocol: 'NEC' },
        { id: 'vol_up', name: 'Vol +', code: 0xE0E0E01F, protocol: 'NEC' },
        { id: 'vol_down', name: 'Vol -', code: 0xE0E0D02F, protocol: 'NEC' },
        { id: 'mute', name: 'Mute', code: 0xE0E0F00F, protocol: 'NEC' },
        { id: 'ch_up', name: 'CH +', code: 0xE0E048B7, protocol: 'NEC' },
        { id: 'ch_down', name: 'CH -', code: 0xE0E008F7, protocol: 'NEC' },
        { id: 'menu', name: 'Menu', code: 0xE0E058A7, protocol: 'NEC' },
        { id: 'exit', name: 'Exit', code: 0xE0E0B44B, protocol: 'NEC' },
        { id: 'up', name: 'Up', code: 0xE0E006F9, protocol: 'NEC' },
        { id: 'down', name: 'Down', code: 0xE0E08679, protocol: 'NEC' },
        { id: 'left', name: 'Left', code: 0xE0E0A659, protocol: 'NEC' },
        { id: 'right', name: 'Right', code: 0xE0E046B9, protocol: 'NEC' },
        { id: 'enter', name: 'Enter', code: 0xE0E016E9, protocol: 'NEC' },
        { id: 'num_1', name: '1', code: 0xE0E020DF, protocol: 'NEC' },
        { id: 'num_2', name: '2', code: 0xE0E0A05F, protocol: 'NEC' },
        { id: 'num_3', name: '3', code: 0xE0E0609F, protocol: 'NEC' },
        { id: 'num_4', name: '4', code: 0xE0E010EF, protocol: 'NEC' },
        { id: 'num_5', name: '5', code: 0xE0E0906F, protocol: 'NEC' },
        { id: 'num_6', name: '6', code: 0xE0E050AF, protocol: 'NEC' },
        { id: 'num_7', name: '7', code: 0xE0E030CF, protocol: 'NEC' },
        { id: 'num_8', name: '8', code: 0xE0E0B04F, protocol: 'NEC' },
        { id: 'num_9', name: '9', code: 0xE0E0708F, protocol: 'NEC' },
        { id: 'num_0', name: '0', code: 0xE0E08877, protocol: 'NEC' },
        { id: 'return', name: 'Return', code: 0xE0E01AE5, protocol: 'NEC' },
        { id: 'guide', name: 'Guide', code: 0xE0E0F20D, protocol: 'NEC' },
        { id: 'info', name: 'Info', code: 0xE0E0F807, protocol: 'NEC' },
        { id: 'tools', name: 'Tools', code: 0xE0E0D22D, protocol: 'NEC' },
      ],
    },
    {
      id: 'tv_lg',
      name: 'TV (LG)',
      actions: [
        { id: 'power', name: 'Power', code: 0x20DF10EF, protocol: 'NEC' },
        { id: 'vol_up', name: 'Vol +', code: 0x20DF40BF, protocol: 'NEC' },
        { id: 'vol_down', name: 'Vol -', code: 0x20DFC03F, protocol: 'NEC' },
        { id: 'mute', name: 'Mute', code: 0x20DF906F, protocol: 'NEC' },
        { id: 'ch_up', name: 'CH +', code: 0x20DF00FF, protocol: 'NEC' },
        { id: 'ch_down', name: 'CH -', code: 0x20DF807F, protocol: 'NEC' },
        { id: 'input', name: 'Input', code: 0x20DFD02F, protocol: 'NEC' },
        { id: 'menu', name: 'Menu', code: 0x20DF50AF, protocol: 'NEC' },
        { id: 'up', name: 'Up', code: 0x20DF02FD, protocol: 'NEC' },
        { id: 'down', name: 'Down', code: 0x20DF827D, protocol: 'NEC' },
        { id: 'left', name: 'Left', code: 0x20DFE01F, protocol: 'NEC' },
        { id: 'right', name: 'Right', code: 0x20DF609F, protocol: 'NEC' },
        { id: 'ok', name: 'OK', code: 0x20DF22DD, protocol: 'NEC' },
        { id: 'back', name: 'Back', code: 0x20DF14EB, protocol: 'NEC' },
        { id: 'home', name: 'Home', code: 0x20DF38C7, protocol: 'NEC' },
        { id: 'num_1', name: '1', code: 0x20DF8877, protocol: 'NEC' },
        { id: 'num_2', name: '2', code: 0x20DF48B7, protocol: 'NEC' },
        { id: 'num_3', name: '3', code: 0x20DFC837, protocol: 'NEC' },
        { id: 'num_4', name: '4', code: 0x20DF28D7, protocol: 'NEC' },
        { id: 'num_5', name: '5', code: 0x20DFA857, protocol: 'NEC' },
        { id: 'num_6', name: '6', code: 0x20DF6897, protocol: 'NEC' },
        { id: 'num_7', name: '7', code: 0x20DF18E7, protocol: 'NEC' },
        { id: 'num_8', name: '8', code: 0x20DF9867, protocol: 'NEC' },
        { id: 'num_9', name: '9', code: 0x20DF58A7, protocol: 'NEC' },
        { id: 'num_0', name: '0', code: 0x20DF708F, protocol: 'NEC' },
      ],
    },
    {
      id: 'soundbar',
      name: 'Soundbar',
      actions: [
        { id: 'power', name: 'Power', code: 0x7E8E11EE, protocol: 'NEC' },
        { id: 'vol_up', name: 'Vol +', code: 0x7E8E41BE, protocol: 'NEC' },
        { id: 'vol_down', name: 'Vol -', code: 0x7E8EC13E, protocol: 'NEC' },
        { id: 'mute', name: 'Mute', code: 0x7E8E916E, protocol: 'NEC' },
        { id: 'input', name: 'Input', code: 0x7E8E51AE, protocol: 'NEC' },
      ],
    },
    {
      id: 'tv_sony',
      name: 'TV (Sony)',
      actions: [
        { id: 'power', name: 'Power', code: 0xA90, protocol: 'SONY', nbits: 12 },
        { id: 'vol_up', name: 'Vol +', code: 0x490, protocol: 'SONY', nbits: 12 },
        { id: 'vol_down', name: 'Vol -', code: 0xC90, protocol: 'SONY', nbits: 12 },
        { id: 'mute', name: 'Mute', code: 0x290, protocol: 'SONY', nbits: 12 },
        { id: 'ch_up', name: 'CH +', code: 0x90, protocol: 'SONY', nbits: 12 },
        { id: 'ch_down', name: 'CH -', code: 0x890, protocol: 'SONY', nbits: 12 },
        { id: 'input', name: 'Input', code: 0x190, protocol: 'SONY', nbits: 12 },
        { id: 'num_1', name: '1', code: 0x10, protocol: 'SONY', nbits: 12 },
        { id: 'num_2', name: '2', code: 0x810, protocol: 'SONY', nbits: 12 },
        { id: 'num_3', name: '3', code: 0x410, protocol: 'SONY', nbits: 12 },
        { id: 'num_4', name: '4', code: 0xC10, protocol: 'SONY', nbits: 12 },
        { id: 'num_5', name: '5', code: 0x210, protocol: 'SONY', nbits: 12 },
        { id: 'num_6', name: '6', code: 0xA10, protocol: 'SONY', nbits: 12 },
        { id: 'num_7', name: '7', code: 0x610, protocol: 'SONY', nbits: 12 },
        { id: 'num_8', name: '8', code: 0xE10, protocol: 'SONY', nbits: 12 },
        { id: 'num_9', name: '9', code: 0x110, protocol: 'SONY', nbits: 12 },
        { id: 'num_0', name: '0', code: 0x910, protocol: 'SONY', nbits: 12 },
        { id: 'up', name: 'Up', code: 0x5B0, protocol: 'SONY', nbits: 12 },
        { id: 'down', name: 'Down', code: 0xDB0, protocol: 'SONY', nbits: 12 },
        { id: 'left', name: 'Left', code: 0xBB0, protocol: 'SONY', nbits: 12 },
        { id: 'right', name: 'Right', code: 0x3B0, protocol: 'SONY', nbits: 12 },
        { id: 'enter', name: 'Enter', code: 0x4B0, protocol: 'SONY', nbits: 12 },
        { id: 'home', name: 'Home', code: 0x7B0, protocol: 'SONY', nbits: 12 },
      ],
    },
    {
      id: 'tv_panasonic',
      name: 'TV (Panasonic)',
      actions: [
        { id: 'power', name: 'Power', code: 0x40040118E8, protocol: 'PANASONIC', nbits: 48 },
        { id: 'vol_up', name: 'Vol +', code: 0x40040118C8, protocol: 'PANASONIC', nbits: 48 },
        { id: 'vol_down', name: 'Vol -', code: 0x4004011828, protocol: 'PANASONIC', nbits: 48 },
        { id: 'mute', name: 'Mute', code: 0x40040118B8, protocol: 'PANASONIC', nbits: 48 },
        { id: 'ch_up', name: 'CH +', code: 0x4004011848, protocol: 'PANASONIC', nbits: 48 },
        { id: 'ch_down', name: 'CH -', code: 0x4004011808, protocol: 'PANASONIC', nbits: 48 },
        { id: 'input', name: 'Input', code: 0x4004011988, protocol: 'PANASONIC', nbits: 48 },
        { id: 'menu', name: 'Menu', code: 0x4004011978, protocol: 'PANASONIC', nbits: 48 },
        { id: 'up', name: 'Up', code: 0x4004011938, protocol: 'PANASONIC', nbits: 48 },
        { id: 'down', name: 'Down', code: 0x4004011918, protocol: 'PANASONIC', nbits: 48 },
        { id: 'home', name: 'Home', code: 0x4004011908, protocol: 'PANASONIC', nbits: 48 },
        { id: 'num_1', name: '1', code: 0x40040119C8, protocol: 'PANASONIC', nbits: 48 },
        { id: 'num_2', name: '2', code: 0x4004011928, protocol: 'PANASONIC', nbits: 48 },
        { id: 'num_3', name: '3', code: 0x4004011A28, protocol: 'PANASONIC', nbits: 48 },
        { id: 'num_4', name: '4', code: 0x4004011968, protocol: 'PANASONIC', nbits: 48 },
        { id: 'num_5', name: '5', code: 0x4004011A68, protocol: 'PANASONIC', nbits: 48 },
        { id: 'num_6', name: '6', code: 0x40040119A8, protocol: 'PANASONIC', nbits: 48 },
        { id: 'num_7', name: '7', code: 0x4004011AA8, protocol: 'PANASONIC', nbits: 48 },
        { id: 'num_8', name: '8', code: 0x4004011828, protocol: 'PANASONIC', nbits: 48 },
        { id: 'num_9', name: '9', code: 0x40040118A8, protocol: 'PANASONIC', nbits: 48 },
        { id: 'num_0', name: '0', code: 0x4004011A08, protocol: 'PANASONIC', nbits: 48 },
      ],
    },
    {
      id: 'tv_sharp',
      name: 'TV (Sharp)',
      actions: [
        { id: 'power', name: 'Power', code: 0x10EF40BF, protocol: 'NEC' },
        { id: 'vol_up', name: 'Vol +', code: 0x10EF20DF, protocol: 'NEC' },
        { id: 'vol_down', name: 'Vol -', code: 0x10EFA05F, protocol: 'NEC' },
        { id: 'mute', name: 'Mute', code: 0x10EFE01F, protocol: 'NEC' },
        { id: 'ch_up', name: 'CH +', code: 0x10EF00FF, protocol: 'NEC' },
        { id: 'ch_down', name: 'CH -', code: 0x10EF807F, protocol: 'NEC' },
        { id: 'input', name: 'Input', code: 0x10EFD02F, protocol: 'NEC' },
        { id: 'num_1', name: '1', code: 0x10EF8877, protocol: 'NEC' },
        { id: 'num_2', name: '2', code: 0x10EF48B7, protocol: 'NEC' },
        { id: 'num_3', name: '3', code: 0x10EFC837, protocol: 'NEC' },
        { id: 'num_4', name: '4', code: 0x10EF28D7, protocol: 'NEC' },
        { id: 'num_5', name: '5', code: 0x10EFA857, protocol: 'NEC' },
        { id: 'num_6', name: '6', code: 0x10EF6897, protocol: 'NEC' },
        { id: 'num_7', name: '7', code: 0x10EF18E7, protocol: 'NEC' },
        { id: 'num_8', name: '8', code: 0x10EF9867, protocol: 'NEC' },
        { id: 'num_9', name: '9', code: 0x10EF58A7, protocol: 'NEC' },
        { id: 'num_0', name: '0', code: 0x10EF708F, protocol: 'NEC' },
      ],
    },
    {
      id: 'dvd',
      name: 'DVD / Blu-ray',
      actions: [
        { id: 'power', name: 'Power', code: 0x20DF10EF, protocol: 'NEC' },
        { id: 'play', name: 'Play', code: 0x20DF2AD5, protocol: 'NEC' },
        { id: 'pause', name: 'Pause', code: 0x20DF0AF5, protocol: 'NEC' },
        { id: 'stop', name: 'Stop', code: 0x20DF8A75, protocol: 'NEC' },
        { id: 'next', name: 'Next', code: 0x20DFD52A, protocol: 'NEC' },
        { id: 'prev', name: 'Prev', code: 0x20DF55AA, protocol: 'NEC' },
        { id: 'fwd', name: 'Fwd', code: 0x20DF35CA, protocol: 'NEC' },
        { id: 'rew', name: 'Rew', code: 0x20DFB54A, protocol: 'NEC' },
        { id: 'eject', name: 'Eject', code: 0x20DF9A65, protocol: 'NEC' },
        { id: 'menu', name: 'Menu', code: 0x20DF50AF, protocol: 'NEC' },
        { id: 'up', name: 'Up', code: 0x20DF02FD, protocol: 'NEC' },
        { id: 'down', name: 'Down', code: 0x20DF827D, protocol: 'NEC' },
        { id: 'left', name: 'Left', code: 0x20DFE01F, protocol: 'NEC' },
        { id: 'right', name: 'Right', code: 0x20DF609F, protocol: 'NEC' },
        { id: 'ok', name: 'OK', code: 0x20DF22DD, protocol: 'NEC' },
        { id: 'back', name: 'Back', code: 0x20DF14EB, protocol: 'NEC' },
      ],
    },
    {
      id: 'projector',
      name: 'Projector (BenQ)',
      actions: [
        { id: 'power', name: 'Power', code: 0x4CB31A2B, protocol: 'NEC' },
        { id: 'source', name: 'Source', code: 0x4CB36B38, protocol: 'NEC' },
        { id: 'menu', name: 'Menu', code: 0x4CB38540, protocol: 'NEC' },
        { id: 'up', name: 'Up', code: 0x4CB30760, protocol: 'NEC' },
        { id: 'down', name: 'Down', code: 0x4CB3E22B, protocol: 'NEC' },
        { id: 'auto', name: 'Auto Sync', code: 0x4CB3C33F, protocol: 'NEC' },
        { id: 'blank', name: 'Blank', code: 0x4CB3226E, protocol: 'NEC' },
        { id: 'volume_up', name: 'Vol +', code: 0x4CB3C837, protocol: 'NEC' },
        { id: 'volume_down', name: 'Vol -', code: 0x4CB348B7, protocol: 'NEC' },
      ],
    },
    {
      id: 'led_rgb',
      name: 'RGB LED Strip',
      actions: [
        { id: 'power', name: 'Power', code: 0xFF609F, protocol: 'NEC' },
        { id: 'white', name: 'White', code: 0xFF906F, protocol: 'NEC' },
        { id: 'red', name: 'Red', code: 0xFFA857, protocol: 'NEC' },
        { id: 'green', name: 'Green', code: 0xFF9867, protocol: 'NEC' },
        { id: 'blue', name: 'Blue', code: 0xFFD827, protocol: 'NEC' },
        { id: 'orange', name: 'Orange', code: 0xFFB24D, protocol: 'NEC' },
        { id: 'pink', name: 'Pink', code: 0xFF6897, protocol: 'NEC' },
        { id: 'yellow', name: 'Yellow', code: 0xFF00FF, protocol: 'NEC' },
        { id: 'rainbow', name: 'Rainbow', code: 0xFF708F, protocol: 'NEC' },
        { id: 'bright_up', name: 'Bright +', code: 0xFF8877, protocol: 'NEC' },
        { id: 'bright_down', name: 'Bright -', code: 0xFF7887, protocol: 'NEC' },
        { id: 'night', name: 'Night Mode', code: 0xFF50AF, protocol: 'NEC' },
        { id: 'timer', name: 'Timer', code: 0xFF7887, protocol: 'NEC' },
      ],
    },
  ],
};
